stages:
  - build



variables:
  CONTAINER_TEST_IMAGE: gitlab.alpha.dev/robrotheram/baldrick

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.alpha.dev
 
build_targeting:
  stage: build
  script:
    - docker build -t gitlab.alpha.dev/robrotheram/baldrick .
    - docker push gitlab.alpha.dev/robrotheram/baldrick